#!/bin/sh
# Reads data from STDIN and draws a frequency histogram. -r assumes
# pre-aggregated data
# Usage: hist [-r] [plot function] [plotchar]
# "plot function" is any valid perl expression, with "x" being the value.
f(){ sort | uniq -c; }
if [ "$1" = '-r' ]; then
	f() cat
	shift
fi
e="$(printf '%s' "${1:-x}" | perl -pe 's/x/\$F[0]/g;s/\\\$F\[0\]/x/g')"
c="${2:-#}"
f | perl -lane 'print "$F[1]\t$F[0]\t", "'"$c"'"x('"$e"')'
